# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - fff

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://contento.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_d3ef682aa9d54805a04b7cb154dcc790 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f1df33ef09bb4eb1a88ebebbfb7f4a39 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: contento.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d3ef682aa9d54805a04b7cb154dcc790 }}/hola:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fff'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_04d6bd79435b42e58c9a9b1dade9fc56 }}
        images: 'contento.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d3ef682aa9d54805a04b7cb154dcc790 }}/hola:${{ github.sha }}'